customhost = "employee.c721kcjdpsrz.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "sootzanjian-employee"
customregion = "us-east-1"
